version: "3.8"

services:
  keycloak:
    container_name: chat-keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    command:
      - "start-dev"
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
      - "--http-port=8081"
