spring:
  application:
    name: Chat API

  profiles:
    active: @spring.profiles.active@

  liquibase:
    change-log: classpath:/db/changelog/master.xml

  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

server:
  port: 8080
  servlet:
    context-path: /api
