spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: sa
    password: Password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  realm: chat-keycloak
  resource: chat-keycloak-front
  auth-server-url: http://localhost:8081/
  public-client: true
  ssl-required: external
  principal-attribute: preferred_username
  bearer-only: true
