spring:
  application:
    name: Chat API

  profiles:
    active: @spring.profiles.active@

  liquibase:
    change-log: classpath:/db/changelog/master.xml

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
  servlet:
    context-path: /api
